"""
AI Assistant router — chat interface with full draft bible context.

Endpoint:
  POST /assistant/chat — streaming chat with context-enriched Sonnet calls
"""
from __future__ import annotations

import json
import logging
import re
import uuid
from datetime import datetime, timedelta, timezone
from typing import Optional

import anthropic
from fastapi import APIRouter, HTTPException
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
from sqlalchemy import select
from sqlalchemy.orm import selectinload

from backend.config import settings
from backend.database import AsyncSessionLocal
from backend.models.player import Player, PlayerProfile, PlayerInjuryProfile, PlayerSchedule
from backend.models.dependency import PlayerDependency, BeatReporterSignal

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/assistant", tags=["assistant"])

MODEL = "claude-sonnet-4-6"
MAX_TOKENS = 1000

SYSTEM_PROMPT = """You are a fantasy football analyst with access to a custom AI-powered draft and season management system. You have been provided with real data from the user's draft bible — player valuations, system grades, dependency flags, injury risk scores, and schedule analysis all generated by the platform's research agents.

Use this data to give specific, grounded advice. Reference the actual numbers and flags in your answers. Don't speak in generalities when you have real data.

When discussing bid ceilings, always explain the two-value system (system value vs market value) and why the gap matters.

When discussing trades, always consider:
- Current trade values from the platform
- Timing flags (sell high / buy low signals)
- The opponent's management style if known
- Playoff schedule implications

Be direct and opinionated. This person wants actionable advice, not hedged disclaimers.

Format your responses using markdown for readability. Use bold for player names and key numbers. Use bullet points for lists of considerations."""


# ---------------------------------------------------------------------------
# Request / Response models
# ---------------------------------------------------------------------------

class ChatMessage(BaseModel):
    role: str  # "user" or "assistant"
    content: str


class ChatRequest(BaseModel):
    message: str
    context_type: str = "general"  # general|player|trade|draft|lineup
    player_ids: list[str] = []
    include_roster: bool = True
    include_opponents: bool = False
    conversation_history: list[ChatMessage] = []


# ---------------------------------------------------------------------------
# Context assembly
# ---------------------------------------------------------------------------

async def build_assistant_context(
    message: str,
    context_type: str,
    player_ids: list[str],
    include_roster: bool,
    include_opponents: bool,
) -> str:
    """
    Build the context block injected into the assistant request.
    Pulls relevant data from the draft bible database.
    """
    sections = []

    # Always include league context
    sections.append("""LEAGUE CONTEXT:
Format: 12-team PPR (1pt per reception)
Budget: $200 auction (skill starters target: $185)
Roster: 1 QB, 2 RB, 2 WR, 1 FLEX (RB/WR/TE), 1 TE, 1 K, 1 DEF, 7 bench
Playoff weeks: 14-17
Positional budget targets: RB=38%, WR=32%, QB=10%, TE=10% of $185
Max realistic bids: RB=$80, WR=$70, QB=$50, TE=$45""")

    async with AsyncSessionLocal() as session:
        # Include explicitly requested players
        explicit_players = []
        if player_ids:
            parsed_ids = []
            for pid in player_ids:
                try:
                    parsed_ids.append(uuid.UUID(pid))
                except (ValueError, TypeError):
                    continue
            if parsed_ids:
                stmt = (
                    select(Player)
                    .options(
                        selectinload(Player.profile),
                        selectinload(Player.injury_profile),
                        selectinload(Player.schedule),
                        selectinload(Player.dependencies),
                        selectinload(Player.beat_signals),
                    )
                    .where(Player.id.in_(parsed_ids))
                )
                result = await session.execute(stmt)
                explicit_players = list(result.scalars().all())
                for player in explicit_players:
                    sections.append(_format_player_context(player))

        # Auto-detect players mentioned in the message
        mentioned = await _find_mentioned_players(session, message)
        explicit_ids = {p.id for p in explicit_players}
        for player in mentioned:
            if player.id not in explicit_ids:
                sections.append(_format_player_context(player))

        # Include top value gaps for draft strategy questions
        if context_type in ("draft", "general"):
            gaps = await _get_top_value_gaps(session)
            if gaps:
                sections.append(gaps)

        # Include recent relevant news
        all_player_ids = [p.id for p in explicit_players] + [p.id for p in mentioned if p.id not in explicit_ids]
        news = await _get_recent_signals(session, all_player_ids)
        if news:
            sections.append(news)

    return "\n\n---\n\n".join(sections)


def _format_player_context(player: Player) -> str:
    """Format a single player's full draft bible context."""
    lines = [f"PLAYER: {player.name} ({player.position}, {player.team_abbr or 'FA'})"]

    # Valuation
    if player.tier:
        lines.append(f"  Tier: {player.tier}")
    if player.recommended_bid_ceiling:
        lines.append(f"  Bid ceiling: ${player.recommended_bid_ceiling}")
    if player.baseline_value:
        lines.append(f"  System value: ${player.baseline_value}")
    if player.market_value:
        lines.append(f"  Market value: ${player.market_value}")
    if player.value_gap and player.value_gap_signal:
        lines.append(f"  Value gap: ${player.value_gap} ({player.value_gap_signal})")
    if player.situation_score:
        lines.append(f"  Situation: {player.situation_score}")
    if player.let_go_threshold:
        lines.append(f"  Let-go threshold: ${player.let_go_threshold}")

    # Profile data
    if player.profile:
        p = player.profile
        if p.role_classification:
            lines.append(f"  Role: {p.role_classification}")
        if p.career_trajectory:
            lines.append(f"  Career trajectory: {p.career_trajectory}")
        if p.clean_season_baseline:
            csb = p.clean_season_baseline
            ppr = csb.get("ppr_points")
            rec = csb.get("receptions")
            yds = csb.get("yards")
            tds = csb.get("tds")
            if ppr:
                lines.append(f"  Clean season baseline: {rec} rec, {yds} yds, {tds} TD, {ppr:.0f} PPR pts")

    # Injury
    if player.injury_profile:
        ip = player.injury_profile
        lines.append(f"  Injury risk: {ip.overall_risk_level or 'unknown'}")
        if ip.post_acl_flag:
            lines.append("  Flag: POST_ACL recovery")
        if ip.workload_cliff_flag:
            lines.append("  Flag: WORKLOAD_CLIFF")
        if ip.risk_adjusted_value_modifier:
            lines.append(f"  Risk modifier: {float(ip.risk_adjusted_value_modifier):+.0%}")

    # Schedule
    if player.schedule:
        s = player.schedule
        parts = []
        if s.early_window_grade:
            parts.append(f"Early: {s.early_window_grade}")
        if s.full_season_grade:
            parts.append(f"Full: {s.full_season_grade}")
        if s.playoff_window_grade:
            parts.append(f"Playoffs: {s.playoff_window_grade}")
        if parts:
            lines.append(f"  Schedule: {', '.join(parts)}")
        if s.bye_in_playoff_window:
            lines.append("  Warning: Bye in playoff window")

    # Dependency flags
    if player.dependencies:
        flag_lines = []
        for dep in player.dependencies:
            flag_str = f"    {dep.flag_type.upper()}"
            if dep.trigger_player_name:
                flag_str += f" (trigger: {dep.trigger_player_name})"
            if dep.reasoning:
                flag_str += f" — {dep.reasoning[:100]}"
            flag_lines.append(flag_str)
        if flag_lines:
            lines.append("  Active flags:")
            lines.extend(flag_lines)

    # Notes
    if player.notes:
        lines.append(f"  Notes: {player.notes}")

    return "\n".join(lines)


async def _find_mentioned_players(session, message: str) -> list[Player]:
    """Find players mentioned by name in the user's message."""
    # Load all players with valuations (only those with tiers are relevant)
    stmt = (
        select(Player)
        .options(
            selectinload(Player.profile),
            selectinload(Player.injury_profile),
            selectinload(Player.schedule),
            selectinload(Player.dependencies),
        )
        .where(Player.tier.isnot(None))
    )
    result = await session.execute(stmt)
    all_players = result.scalars().all()

    msg_lower = message.lower()
    found = []

    for player in all_players:
        if not player.name:
            continue
        parts = player.name.split()
        # Match on last name (3+ chars to avoid false positives)
        last_name = parts[-1].lower() if parts else ""
        if len(last_name) >= 3 and last_name in msg_lower:
            # Verify it's a word boundary match
            pattern = r'\b' + re.escape(last_name) + r'\b'
            if re.search(pattern, msg_lower):
                found.append(player)

    # Limit to 5 to avoid massive context
    return found[:5]


async def _get_top_value_gaps(session) -> str | None:
    """Get top 10 players where system value exceeds market value."""
    stmt = (
        select(Player)
        .where(
            Player.value_gap.isnot(None),
            Player.value_gap > 0,
            Player.tier.isnot(None),
        )
        .order_by(Player.value_gap.desc())
        .limit(10)
    )
    result = await session.execute(stmt)
    players = result.scalars().all()

    if not players:
        return None

    lines = ["TOP VALUE GAPS (system value > market value — buy-low targets):"]
    for p in players:
        lines.append(
            f"  {p.name} ({p.position}, {p.team_abbr}) — "
            f"Gap: +${p.value_gap}, Ceil: ${p.recommended_bid_ceiling}, T{p.tier}"
        )
    return "\n".join(lines)


async def _get_recent_signals(session, player_ids: list) -> str | None:
    """Get recent beat reporter signals for relevant players."""
    cutoff = datetime.now(timezone.utc) - timedelta(days=14)
    stmt = select(BeatReporterSignal).where(
        BeatReporterSignal.flagged_at >= cutoff
    ).order_by(BeatReporterSignal.flagged_at.desc()).limit(10)

    # If we have specific player IDs, prioritize those
    if player_ids:
        stmt = select(BeatReporterSignal).where(
            BeatReporterSignal.player_id.in_(player_ids),
            BeatReporterSignal.flagged_at >= cutoff,
        ).order_by(BeatReporterSignal.flagged_at.desc()).limit(10)

    result = await session.execute(stmt)
    signals = result.scalars().all()

    if not signals:
        return None

    lines = ["RECENT NEWS (last 14 days):"]
    for s in signals:
        date_str = s.flagged_at.strftime("%b %d") if s.flagged_at else "?"
        lines.append(f"  [{date_str}] {s.signal_type}: {s.raw_text or 'No details'}")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Streaming endpoint
# ---------------------------------------------------------------------------

@router.post("/chat")
async def chat(request: ChatRequest):
    """Stream a response from the AI assistant with full draft bible context."""
    if not request.message.strip():
        raise HTTPException(status_code=400, detail="Message cannot be empty")

    # Build context from database
    context = await build_assistant_context(
        message=request.message,
        context_type=request.context_type,
        player_ids=request.player_ids,
        include_roster=request.include_roster,
        include_opponents=request.include_opponents,
    )

    # Build messages list with conversation history
    messages = []
    for msg in request.conversation_history[-10:]:  # Last 10 messages max
        messages.append({"role": msg.role, "content": msg.content})

    # Add current message with context
    user_content = f"""Here is the relevant data from my draft bible:

{context}

---

My question: {request.message}"""

    messages.append({"role": "user", "content": user_content})

    async def generate():
        try:
            client = anthropic.AsyncAnthropic(api_key=settings.anthropic_api_key)
            async with client.messages.stream(
                model=MODEL,
                max_tokens=MAX_TOKENS,
                system=SYSTEM_PROMPT,
                messages=messages,
            ) as stream:
                async for text in stream.text_stream:
                    yield f"data: {json.dumps({'text': text})}\n\n"
            yield "data: [DONE]\n\n"
        except anthropic.APIError as e:
            logger.error("Anthropic API error in assistant: %s", e)
            yield f"data: {json.dumps({'error': str(e)})}\n\n"
            yield "data: [DONE]\n\n"
        except Exception as e:
            logger.error("Unexpected error in assistant: %s", e)
            yield f"data: {json.dumps({'error': 'An unexpected error occurred'})}\n\n"
            yield "data: [DONE]\n\n"

    return StreamingResponse(
        generate(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "X-Accel-Buffering": "no",
        },
    )
