"""add market_value_metadata table

Revision ID: 4bde60987b65
Revises: a066cc8eebeb
Create Date: 2026-05-06 12:19:07.291561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bde60987b65'
down_revision: Union[str, None] = 'a066cc8eebeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_value_metadata',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('is_current_season', sa.Boolean(), nullable=False),
    sa.Column('player_count', sa.Integer(), nullable=False),
    sa.Column('refreshed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('market_value_metadata')
    # ### end Alembic commands ###
