"""add_user_preferences_table

Revision ID: 72257c0fcc6b
Revises: e699ea58b823
Create Date: 2026-05-05 11:37:18.861960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '72257c0fcc6b'
down_revision: Union[str, None] = 'e699ea58b823'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('preference_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_preferences_entity_id'), 'user_preferences', ['entity_id'], unique=False)
    op.create_index(op.f('ix_user_preferences_preference_type'), 'user_preferences', ['preference_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_preferences_preference_type'), table_name='user_preferences')
    op.drop_index(op.f('ix_user_preferences_entity_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    # ### end Alembic commands ###
