"""add_unique_constraint_user_leagues

Revision ID: 877b4d574363
Revises: e5080c08637b
Create Date: 2026-05-16 13:39:19.573433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '877b4d574363'
down_revision: Union[str, None] = 'e5080c08637b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_leagues_user_platform_league', 'user_leagues', ['user_id', 'platform', 'league_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_leagues_user_platform_league', 'user_leagues', type_='unique')
    # ### end Alembic commands ###
