"""add oline numerics to team_systems

Revision ID: a066cc8eebeb
Revises: 72257c0fcc6b
Create Date: 2026-05-05 18:02:17.482357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a066cc8eebeb'
down_revision: Union[str, None] = '72257c0fcc6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_systems', sa.Column('sack_rate', sa.Numeric(precision=5, scale=4), nullable=True))
    op.add_column('team_systems', sa.Column('avg_time_to_throw', sa.Numeric(precision=4, scale=3), nullable=True))
    op.add_column('team_systems', sa.Column('qb_mobility', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_systems', 'qb_mobility')
    op.drop_column('team_systems', 'avg_time_to_throw')
    op.drop_column('team_systems', 'sack_rate')
    # ### end Alembic commands ###
