"""add agent_cache and api_usage_log tables

Revision ID: a14e9307405a
Revises: 24b03f427121
Create Date: 2026-04-30 10:51:45.809886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a14e9307405a'
down_revision: Union[str, None] = '24b03f427121'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_cache',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_name', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('output_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_name', 'entity_id', 'input_hash', name='uq_agent_cache_key')
    )
    op.create_index(op.f('ix_agent_cache_agent_name'), 'agent_cache', ['agent_name'], unique=False)
    op.create_table('api_usage_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_name', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost_usd', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('cache_hit', sa.Boolean(), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('called_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_usage_log_agent_name'), 'api_usage_log', ['agent_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_usage_log_agent_name'), table_name='api_usage_log')
    op.drop_table('api_usage_log')
    op.drop_index(op.f('ix_agent_cache_agent_name'), table_name='agent_cache')
    op.drop_table('agent_cache')
    # ### end Alembic commands ###
