"""stage28_platform_credentials_manager_map

Revision ID: e5080c08637b
Revises: 407ae5ce903c
Create Date: 2026-05-15 08:57:42.797087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e5080c08637b'
down_revision: Union[str, None] = '407ae5ce903c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_credentials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('espn_s2', sa.Text(), nullable=True),
    sa.Column('swid', sa.Text(), nullable=True),
    sa.Column('sleeper_user_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'platform', name='uq_platform_credentials_user_platform')
    )
    op.create_index(op.f('ix_platform_credentials_user_id'), 'platform_credentials', ['user_id'], unique=False)
    op.add_column('user_leagues', sa.Column('manager_map', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_leagues', 'manager_map')
    op.drop_index(op.f('ix_platform_credentials_user_id'), table_name='platform_credentials')
    op.drop_table('platform_credentials')
    # ### end Alembic commands ###
