"""add_league_settings_table

Revision ID: efb14aff0790
Revises: fcf87ffc5c90
Create Date: 2026-05-01 10:44:42.810335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'efb14aff0790'
down_revision: Union[str, None] = 'fcf87ffc5c90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('league_settings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('scoring_format', sa.String(length=10), nullable=False),
    sa.Column('team_count', sa.Integer(), nullable=False),
    sa.Column('auction_budget', sa.Integer(), nullable=False),
    sa.Column('min_bid', sa.Integer(), nullable=False),
    sa.Column('skill_starter_budget', sa.Integer(), nullable=False),
    sa.Column('league_skill_dollar_pool', sa.Integer(), nullable=False),
    sa.Column('total_roster_size', sa.Integer(), nullable=False),
    sa.Column('starting_lineup_size', sa.Integer(), nullable=False),
    sa.Column('roster_slots', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('positional_budget_pcts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('replacement_level_ppr', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('max_realistic_bid', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('typical_bid_ranges', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('league_settings')
    # ### end Alembic commands ###
