"""add bye_in_playoff_window to player_schedules

Revision ID: fcf87ffc5c90
Revises: a14e9307405a
Create Date: 2026-04-30 15:56:24.421358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcf87ffc5c90'
down_revision: Union[str, None] = 'a14e9307405a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_schedules', sa.Column('bye_in_playoff_window', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_schedules', 'bye_in_playoff_window')
    # ### end Alembic commands ###
