"""
Email templates. Pure functions: each returns ``(subject, html, text)`` and does
no I/O, no database reads, and no settings reads beyond the constants imported
below — so every one of them is directly testable.

NO LITERAL PERCENTAGES OR PRICES IN THIS FILE. Every number in the copy is read
from REFERRAL_PROGRAM / TIER_LIMITS in backend/models/user.py, which is the single
source of truth. A "20" typed into a template string is exactly the drift those
dicts exist to prevent: the coupon would say one thing and the email another.

HTML RULES, imposed by email clients rather than by taste:
  * Inline styles only. Gmail strips <style> blocks, so a stylesheet would leave
    the message unstyled for a large share of recipients.
  * Table-based layout, fixed 600px maximum. Outlook renders with Word's engine,
    which does not lay out modern CSS; nested tables are what it does understand.
  * Every interpolated value goes through html.escape. A display name comes from
    the user and reaches the message unfiltered otherwise.
  * The plain-text alternative is written as text, not generated by stripping
    tags. Some clients show it, and spam filters read it.
"""
from __future__ import annotations

import html
from typing import Optional

from backend.models.user import REFERRAL_PROGRAM, TIER_LIMITS

# Brand navy, matching --color-brand in frontend/src/index.css.
_BRAND = "#2a3d8f"
_INK = "#1c1f2e"
_MUTED = "#5a6072"
_PAGE_BG = "#f4f5f7"
_CARD_BG = "#ffffff"
_BORDER = "#e2e4ea"

_FONT = (
    "-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,"
    "Helvetica,Arial,sans-serif"
)

# What Rook is, in the two sentences a first email gets to spend on it.
_WHAT_ROOK_IS = (
    "Rook builds its own player valuations from raw NFL data instead of "
    "reselling someone else's projections, then gives you live bid and pick "
    "recommendations while your draft is running. It works with Yahoo, ESPN "
    "and Sleeper, in both auction and snake leagues."
)


def _esc(value: Optional[str]) -> str:
    """HTML-escape a value, quotes included, treating None as empty."""
    return html.escape(value or "", quote=True)


def _greeting_name(display_name: Optional[str]) -> str:
    """First name if we have one, else a neutral address.

    Only the first word: users type "Stephen Dubois" into the name field and
    "Hi Stephen Dubois," reads like a form letter.
    """
    name = (display_name or "").strip()
    return name.split()[0] if name else "there"


# ---------------------------------------------------------------------------
# HTML building blocks
# ---------------------------------------------------------------------------

def _paragraph(text_html: str) -> str:
    return (
        f'<p style="margin:0 0 16px 0;font-size:16px;line-height:24px;'
        f'color:{_INK};">{text_html}</p>'
    )


def _code_block(code: str, caption: str) -> str:
    """The discount or referral code, set large enough to read off a phone."""
    return (
        f'<table role="presentation" width="100%" cellpadding="0" '
        f'cellspacing="0" border="0" style="margin:0 0 20px 0;">'
        f'<tr><td align="center" style="background:{_PAGE_BG};'
        f'border:1px solid {_BORDER};border-radius:8px;padding:18px 12px;">'
        f'<div style="font-size:12px;letter-spacing:0.08em;text-transform:'
        f'uppercase;color:{_MUTED};font-family:{_FONT};margin-bottom:8px;">'
        f'{_esc(caption)}</div>'
        f'<div style="font-size:26px;font-weight:700;letter-spacing:0.12em;'
        f'color:{_INK};font-family:Menlo,Consolas,monospace;">'
        f'{_esc(code)}</div>'
        f'</td></tr></table>'
    )


def _button(href: str, label: str) -> str:
    """A bulletproof-enough CTA: a table cell with a background and a link."""
    return (
        f'<table role="presentation" cellpadding="0" cellspacing="0" '
        f'border="0" style="margin:0 0 24px 0;">'
        f'<tr><td align="center" style="background:{_BRAND};border-radius:6px;">'
        f'<a href="{_esc(href)}" style="display:inline-block;padding:13px 26px;'
        f'font-family:{_FONT};font-size:16px;font-weight:600;color:#ffffff;'
        f'text-decoration:none;">{_esc(label)}</a>'
        f'</td></tr></table>'
    )


def _promotional_footer(
    *, app_url: str, unsubscribe_url: str, postal_address: str
) -> str:
    """The CAN-SPAM footer: who sent this, where they are, how to stop it.

    The postal address and the unsubscribe link are both legally required on a
    commercial message. EmailService refuses to send a promotional template when
    the address is not configured, so an empty string here should be unreachable.
    """
    return (
        f'<tr><td style="padding:20px 32px 28px 32px;border-top:1px solid '
        f'{_BORDER};font-family:{_FONT};font-size:12px;line-height:19px;'
        f'color:{_MUTED};">'
        f'<div style="margin-bottom:8px;">'
        f'You are receiving this because you created a Rook account at '
        f'<a href="{_esc(app_url)}" style="color:{_MUTED};">{_esc(app_url)}</a>.'
        f'</div>'
        f'<div style="margin-bottom:8px;">'
        f'<a href="{_esc(unsubscribe_url)}" style="color:{_MUTED};'
        f'text-decoration:underline;">Unsubscribe from Rook emails</a>'
        f'</div>'
        f'<div>{_esc(postal_address)}</div>'
        f'</td></tr>'
    )


def _document(*, preheader: str, body_rows: str, footer_row: str) -> str:
    """Wrap body rows in the outer table shell.

    The preheader is the grey line a client shows next to the subject in the
    inbox list. Left out, it fills with whatever text comes first, which is
    usually the logo alt text.
    """
    return (
        f'<div style="background:{_PAGE_BG};margin:0;padding:0;">'
        f'<span style="display:none;font-size:1px;color:{_PAGE_BG};'
        f'max-height:0;overflow:hidden;">{_esc(preheader)}</span>'
        f'<table role="presentation" width="100%" cellpadding="0" '
        f'cellspacing="0" border="0" style="background:{_PAGE_BG};'
        f'padding:24px 0;">'
        f'<tr><td align="center" style="padding:0 12px;">'
        f'<table role="presentation" width="600" cellpadding="0" '
        f'cellspacing="0" border="0" style="width:100%;max-width:600px;'
        f'background:{_CARD_BG};border:1px solid {_BORDER};border-radius:10px;">'
        f'<tr><td style="padding:28px 32px 8px 32px;font-family:{_FONT};'
        f'font-size:20px;font-weight:700;color:{_BRAND};">Rook</td></tr>'
        f'{body_rows}'
        f'{footer_row}'
        f'</table></td></tr></table></div>'
    )


def _text_footer(*, app_url: str, unsubscribe_url: str, postal_address: str) -> str:
    return (
        "\n"
        "--\n"
        f"You are receiving this because you created a Rook account at {app_url}\n"
        f"Unsubscribe: {unsubscribe_url}\n"
        f"{postal_address}\n"
    )


# ---------------------------------------------------------------------------
# Templates
# ---------------------------------------------------------------------------

def welcome_email(
    *,
    display_name: Optional[str],
    promo_code: str,
    referral_code: str,
    app_url: str,
    unsubscribe_url: str,
    postal_address: str,
) -> tuple[str, str, str]:
    """The email a new free signup gets: what Rook is, their discount code, and
    their own referral code.

    PROMOTIONAL. Its primary purpose is to sell a subscription, so it carries the
    unsubscribe link and the postal address.
    """
    welcome_pct = REFERRAL_PROGRAM["welcome_percent_off"]
    referred_pct = REFERRAL_PROGRAM["referred_percent_off"]
    per_referral = REFERRAL_PROGRAM["referrer_percent_off_per_referral"]
    cap = REFERRAL_PROGRAM["referrer_percent_off_cap"]
    standard_monthly = TIER_LIMITS["standard"]["price_monthly_usd"]

    name = _greeting_name(display_name)
    subject = f"Welcome to Rook — here is {welcome_pct}% off your first month"
    preheader = (
        f"Your code is {promo_code}. It takes {welcome_pct}% off your first "
        f"month on any monthly plan."
    )

    body = (
        f'<tr><td style="padding:8px 32px 4px 32px;font-family:{_FONT};">'
        + _paragraph(f"Hi {_esc(name)},")
        + _paragraph(
            "Thanks for signing up. Your free account is ready to use right now."
        )
        + _paragraph(_esc(_WHAT_ROOK_IS))
        + _paragraph(
            f"When you are ready to upgrade, this code takes "
            f"<strong>{welcome_pct}% off your first month</strong>. Standard is "
            f"${standard_monthly} a month, and the code works on any monthly "
            f"plan. Enter it at checkout."
        )
        + _code_block(promo_code, "Your first-month discount code")
        + _button(app_url, "Open Rook")
        + _paragraph(
            f"You also have your own referral code. Anyone who uses it gets "
            f"<strong>{referred_pct}% off their first month</strong>, and every "
            f"person who does adds <strong>{per_referral}% off your own monthly "
            f"bill</strong> — up to {cap}%, for as long as you stay subscribed."
        )
        + _code_block(referral_code, "Your referral code")
        + "</td></tr>"
    )

    html_body = _document(
        preheader=preheader,
        body_rows=body,
        footer_row=_promotional_footer(
            app_url=app_url,
            unsubscribe_url=unsubscribe_url,
            postal_address=postal_address,
        ),
    )

    text = (
        f"Hi {name},\n\n"
        "Thanks for signing up. Your free account is ready to use right now.\n\n"
        f"{_WHAT_ROOK_IS}\n\n"
        f"When you are ready to upgrade, this code takes {welcome_pct}% off your "
        f"first month. Standard is ${standard_monthly} a month, and the code "
        "works on any monthly plan. Enter it at checkout.\n\n"
        f"  Your first-month discount code:  {promo_code}\n\n"
        f"Open Rook: {app_url}\n\n"
        f"You also have your own referral code. Anyone who uses it gets "
        f"{referred_pct}% off their first month, and every person who does adds "
        f"{per_referral}% off your own monthly bill - up to {cap}%, for as long "
        "as you stay subscribed.\n\n"
        f"  Your referral code:  {referral_code}\n"
        + _text_footer(
            app_url=app_url,
            unsubscribe_url=unsubscribe_url,
            postal_address=postal_address,
        )
    )
    return subject, html_body, text


def referral_reward_email(
    *,
    display_name: Optional[str],
    new_total_percent: int,
    referral_count: int,
    app_url: str,
    unsubscribe_url: str,
    postal_address: str,
) -> tuple[str, str, str]:
    """The email a REFERRER gets when someone subscribes with their code.

    WHAT THIS MESSAGE DELIBERATELY DOES NOT CONTAIN: any identifying detail about
    the person who redeemed the code — no name, no email address, no signup date.
    The referrer learns only their own new total and their own count. Same rule
    as backend/routers/feedback.py, which files a report under the user's opaque
    id and never their address: user PII does not leave the app, and here it
    would leave to a THIRD PARTY who happens to know the redeemer.

    PROMOTIONAL. Carries the unsubscribe link and the postal address.
    """
    per_referral = REFERRAL_PROGRAM["referrer_percent_off_per_referral"]
    cap = REFERRAL_PROGRAM["referrer_percent_off_cap"]

    name = _greeting_name(display_name)
    friends = "referral" if referral_count == 1 else "referrals"
    subject = f"Your Rook discount is now {new_total_percent}% off"
    preheader = (
        f"Someone subscribed with your referral code. You are now at "
        f"{new_total_percent}% off every month."
    )

    if new_total_percent >= cap:
        next_step = (
            f"That is the maximum — {cap}% is as high as the referral discount "
            "goes."
        )
    else:
        next_step = (
            f"Each additional referral adds another {per_referral}%, up to {cap}%."
        )

    body = (
        f'<tr><td style="padding:8px 32px 4px 32px;font-family:{_FONT};">'
        + _paragraph(f"Hi {_esc(name)},")
        + _paragraph(
            "Someone just subscribed using your referral code. Your discount has "
            "gone up."
        )
        + _code_block(f"{new_total_percent}% off", "Your new monthly discount")
        + _paragraph(
            f"That is {referral_count} confirmed {friends}. {_esc(next_step)} "
            "The discount applies to every monthly bill for as long as you stay "
            "subscribed, and it is applied automatically — there is nothing to "
            "enter."
        )
        + _button(f"{app_url.rstrip('/')}/account", "View your account")
        + "</td></tr>"
    )

    html_body = _document(
        preheader=preheader,
        body_rows=body,
        footer_row=_promotional_footer(
            app_url=app_url,
            unsubscribe_url=unsubscribe_url,
            postal_address=postal_address,
        ),
    )

    text = (
        f"Hi {name},\n\n"
        "Someone just subscribed using your referral code. Your discount has "
        "gone up.\n\n"
        f"  Your new monthly discount:  {new_total_percent}% off\n\n"
        f"That is {referral_count} confirmed {friends}. {next_step} The discount "
        "applies to every monthly bill for as long as you stay subscribed, and "
        "it is applied automatically - there is nothing to enter.\n\n"
        f"View your account: {app_url.rstrip('/')}/account\n"
        + _text_footer(
            app_url=app_url,
            unsubscribe_url=unsubscribe_url,
            postal_address=postal_address,
        )
    )
    return subject, html_body, text
